# Generated by Django 3.0.7 on 2020-09-13 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200912_2150'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='VegProduct',
        ),
    ]
