# Generated by Django 3.0.7 on 2020-09-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_nonvegproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='VeganProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='', upload_to='shop/img')),
            ],
        ),
    ]
