# Generated by Django 3.0.7 on 2020-09-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_veganproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonvegproduct',
            name='quantity',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='veganproduct',
            name='quantity',
            field=models.IntegerField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='vegproduct',
            name='quantity',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
