# Generated by Django 3.0.7 on 2020-09-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20200914_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonvegproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='veganproduct',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='vegproduct',
            name='quantity',
        ),
    ]
